//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RasTop.rc
//
#define IDOK2                           2
#define ID_SAVE                         3
#define ID_EXPORT                       4
#define ID_PROCESS                      5
#define IDD_DIALOG_COLORTOOL            103
#define ID_INDICATOR_ATOM               111
#define ID_INDICATOR_ATOM_NAME          112
#define ID_INDICATOR_NULL               113
#define ID_INDICATOR_GROUP              114
#define ID_INDICATOR_GROUP_NAME         115
#define ID_INDICATOR_CHAIN              116
#define ID_INDICATOR_CHAIN_NAME         117
#define ID_INDICATOR_XCOOR              118
#define ID_INDICATOR_YCOOR              119
#define ID_INDICATOR_ZCOOR              120
#define ID_INDICATOR_COOR_NAME          121
#define IDR_MAINFRAME                   128
#define IDB_INFOPOINTEROFF              130
#define IDB_INFOPOINTERON               131
#define IDR_SELECTIONBAR                132
#define IDD_ABOUTRASTOP                 133
#define IDR_SCRIPTBAR                   134
#define IDR_RASTYPE                     135
#define IDC_RASCURSOR                   136
#define IDR_RASVIEW                     137
#define IDD_DIALOG_SETVALUE             149
#define IDD_SAVE_MOLECULARFILE          150
#define IDD_SAVE_SCRIPT                 151
#define IDD_SAVE_IMAGE                  152
#define IDD_MOLECULAR_FILE              153
#define IDD_PREFERENCES                 154
#define IDD_MOLECULE_CHANGE             155
#define IDD_COMMANDVIEW                 156
#define IDD_LABEL_SETTINGS              157
#define IDD_SELECT_EXPRESSION           158
#define IDC_PICKINGCURSOR               159
#define IDC_PICKINGPLUS                 160
#define IDC_PICKINGMINUS                161
#define IDD_DIALOG_SHOW                 162
#define IDD_DIALOG_COMMAND              163
#define IDB_LIGHT_OFF                   164
#define IDD_COMMANDVIEW_BIG             165
#define IDB_LIGHT_ON                    166
#define IDB_LIGHT_SCRIPT                167
#define IDB_LIGHT_PAUSE                 168
#define IDB_COMMAND_CLOSED              169
#define IDB_COMMAND_CLOSEU              170
#define IDR_TOOLBAR_EXPRESSION          171
#define IDB_LIGHT_STOP                  172
#define IDB_RASTOP                      173
#define IDC_ITEMBOX                     175
#define IDD_DIALOG_NEWSET               176
#define IDD_DIALOG_LIGHTSOURCE          177
#define IDC_ELEMENTBOX                  178
#define IDC_PROPERTYBOX                 179
#define IDC_RENDERINGBOX                180
#define IDC_USERBOX                     181
#define IDC_USERSELECTION               182
#define IDD_LOADPREFS                   183
#define IDD_DIALOG_CMDWND               184
#define IDC_PREFS_CMDCOL                185
#define IDC_PREFS_CMDCOLBKG             186
#define IDC_SCRIPTBOX                   187
#define IDC_INFOLINE                    1002
#define IDD_HARDWARE                    1020
#define IDD_INFOTEXT                    1021
#define IDC_ROTATEX                     1029
#define IDC_ROTATEY                     1030
#define IDC_ROTATEZ                     1031
#define IDC_STATIC_CMNDLINE             1038
#define IDC_STATIC_SLAB                 1039
#define IDC_STATIC_LIGHT                1040
#define IDC_STATIC_SPECULAR             1041
#define IDC_RADIO_ROTATE                1042
#define IDC_RADIO_TRANSLATE             1043
#define IDC_STATIC_DEPTH                1044
#define IDC_STATIC_SHADE                1045
#define IDC_SLID_LIGHT                  1046
#define IDC_BUTTON_SPIN                 1047
#define IDC_BUTTON_AUTO                 1048
#define IDC_SLID_SLAB                   1049
#define IDC_BUTTON_RESET                1050
#define IDC_SPIN_SPECULAR               1051
#define IDC_SLID_DEPTH                  1052
#define IDC_SPIN_DEPTH                  1053
#define IDC_SPIN_SHADE                  1054
#define IDC_INFOPOINTER                 1055
#define IDC_EDIT_VALUE                  1056
#define IDC_SPIN_SLAB                   1057
#define IDC_BUTTON_WORLD                1058
#define IDC_TEX_COMMENTS                1059
#define IDC_BUTTON_DEPTHCUE             1060
#define IDC_TEX_VALUE                   1061
#define IDC_BUTTON_SLAB                 1062
#define IDC_BUTTON_DEPTH                1063
#define IDC_RASMOL_STATUS               1064
#define IDC_BUTTON_CLOSE_COMMAND        1065
#define IDC_SAVE_PDB                    1066
#define IDC_SAVE_MDL                    1067
#define IDC_SAVE_XYZ                    1068
#define IDC_SAVE_CIF                    1069
#define IDC_SAVE_SCRIPT                 1070
#define IDC_SAVE_MOLSCRIPT              1071
#define IDC_SAVE_KINEMAGE               1072
#define IDC_MAGEDETAIL                  1073
#define IDC_SAVE_POVRAY                 1074
#define IDC_SAVE_VMRL                   1075
#define IDC_SAVE_POVRAY3                1076
#define IDC_SAVE_PHIPSI                 1077
#define IDC_SAVE_RDF                    1078
#define IDC_SAVE_RPP                    1079
#define IDC_IMAGE_VECTPS                1080
#define IDC_IMAGE_PPM                   1081
#define IDC_IMAGE_PPM2                  1082
#define IDC_IMAGE_PICT                  1083
#define IDC_IMAGE_IRIS                  1084
#define IDC_IMAGE_SUNRLE                1085
#define IDC_IMAGE_SUN                   1086
#define IDC_IMAGE_BMP                   1087
#define IDC_IMAGE_GIF                   1088
#define IDC_IMAGE_EPSF                  1089
#define IDC_IMAGE_MONOPS                1090
#define IDC_IMAGE_SIZEX                 1091
#define IDC_IMAGE_SIZEY                 1092
#define IDC_IMAGE_ENABLEVECTPS          1093
#define IDC_EDIT_MOLECULAR_FILE         1094
#define IDC_MOLECULE_NAME               1095
#define IDC_MOLECULE_FORMAT             1096
#define IDC_ZOOMEDIT                    1097
#define IDC_MOUSE_RASMOL                1098
#define IDC_MOUSE_QUANTA                1099
#define IDC_MOUSE_INSIGHT               1100
#define IDC_MOUSE_SYBYL                 1101
#define ID_MOLECULE_SEQ_FALSE           1102
#define ID_MOLECULE_SEQ_TRUE            1103
#define ID_COORD_MOL                    1104
#define ID_COORD_WORLD                  1105
#define ID_COORD_ABS                    1106
#define IDC_LABEL_FORMAT                1107
#define IDC_LABEL_FONTSIZE              1108
#define IDC_LABEL_STROKE                1109
#define IDC_EXPRESSION                  1110
#define IDC_LABEL_FS                    1111
#define IDC_LABEL_PS                    1112
#define IDC_BUDDY_SPEC                  1122
#define IDC_BUDDY_SHADE                 1123
#define IDC_BUDDY_DEPTH                 1124
#define IDC_BUDDY_SLAB                  1125
#define IDC_PANNEL_SIZE                 1127
#define IDC_ITEMCOLOR                   1128
#define IDC_PANNEL_COLOR                1129
#define IDC_EDIT_HELPSOURCE             1133
#define IDC_BROWSE                      1134
#define IDC_EDIT_DEFAULTREPRES          1135
#define IDC_LIGHTX                      1136
#define IDC_LIGHTY                      1137
#define IDC_LIGHTZ                      1138
#define IDC_LIGHTXBUDDY                 1144
#define IDC_LIGHTYBUDDY                 1145
#define IDC_LIGHTZBUDDY                 1146
#define ID_LIGHT_DEFAULT                1147
#define IDC_BROWSE_DEFAULTREPRES        1148
#define IDC_EDIT_LOADPREFS              1149
#define IDC_BROWSE_LOADPREFS            1150
#define IDC_BUTTON_TRACK                1151
#define IDC_SHOWDATA                    1152
#define IDC_MOLECULARDATA               1153
#define ID_COORD_SCREEN                 1154
#define IDC_CMDWNDTEXT                  1155
#define ID_FILE_OPEN_AS                 32774
#define ID_FILE_CLOSEDISPLAY            32775
#define ID_LOADSCRIPT                   32778
#define ID_SAVESCRIPT                   32779
#define ID_MOLECULEINFO                 32785
#define ID_DOTS                         32786
#define ID_DOTSON                       32787
#define ID_DOTSOFF                      32788
#define ID_LABELS_ON                    32791
#define ID_LABELS_OFF                   32793
#define ID_LABELS_DEFAULT               32794
#define ID_SELECT_ALL                   32797
#define ID_STATICROTX270                32811
#define ID_STATICROTX180                32812
#define ID_STATICROTX90                 32813
#define ID_STATICROTZ90                 32815
#define ID_STATICROTZ180                32816
#define ID_STATICROTZ270                32817
#define ID_STATICROTY90                 32818
#define ID_STATICROTY180                32819
#define ID_STATICROTY270                32820
#define ID_IMAGE_BMP                    32827
#define ID_IMAGE_GIF                    32828
#define ID_IMAGE_EPSF                   32829
#define ID_IMAGE_PPM                    32830
#define ID_IMAGE_RAST                   32831
#define ID_MOLECULE_PDB                 32832
#define ID_MOLECULE_ALCHEMY             32833
#define ID_SCRIPT_RASMOL                32834
#define ID_SCRIPT_KINEMAGE              32835
#define ID_SCRIPT_MOLSCRIPT             32836
#define ID_SCRIPTLOAD_RASMOL            32838
#define ID_DISPLAY_WIREFRAME            32840
#define ID_DISPLAY_BACKBONE             32841
#define ID_DISPLAY_STICKS               32842
#define ID_DISPLAY_SPACEFILL            32843
#define ID_DISPLAY_BALLANDSTICK         32844
#define ID_DISPLAY_RIBBONS              32845
#define ID_DISPLAY_STRANDS              32846
#define ID_DISPLAY_CARTOONS             32847
#define ID_VIEW_STEREO                  32848
#define ID_VIEW_SPECULAR                32849
#define ID_VIEW_SHADOWS                 32850
#define ID_VIEW_SLABMODE                32851
#define ID_SELECT_HYDROGENS             32852
#define ID_SELECT_HETE_ATOMS            32853
#define ID_HELP_RASMOL                  32854
#define ID_COLOUR_CPK                   32855
#define ID_COLOUR_SHAPELY               32856
#define ID_COLOUR_STRUCTURE             32857
#define ID_COLOUR_GROUP                 32858
#define ID_COLOUR_CHAIN                 32859
#define ID_COLOUR_TEMPERATURE           32860
#define ID_COLOUR_USER                  32861
#define ID_COLOUR_MONO                  32863
#define ID_SET_SLAB_REJECT              32865
#define ID_SET_SLAB_HALF                32866
#define ID_SET_SLAB_HOLLOW              32867
#define ID_SET_SLAB_SOLID               32868
#define ID_SET_SLAB_SECTION             32869
#define IDD_MOLECULEISEQ                32870
#define IDD_MOLECULESYM                 32871
#define ID_MOLECULE_SEQ                 32872
#define ID_MOLECULE_SYM                 32873
#define ID_MOLECULE_STRUC               32874
#define ID_DISPLAY_AXES                 32875
#define ID_COLOR_MOLECULE               32877
#define ID_COLOR_BACKGROUND             32878
#define ID_COLOUR_CHARGE                32879
#define ID_COLOR_ATOM                   32880
#define ID_COLOR_BONDS                  32881
#define ID_COLOR_RIBBONS                32882
#define ID_COLOR_LABELS                 32883
#define ID_COLOR_DOTS                   32884
#define ID_COLOR_HBONDS                 32885
#define ID_COLOR_SSBONDS                32886
#define ID_SELECT_SHOW                  32888
#define ID_DISPLAY_RIBBONS_OFF          32889
#define ID_COLOR_RIBBONS_NONE           32891
#define ID_SET_RIBBONS_SIZE             32892
#define ID_EDIT_RASMOL_COMMAND          32893
#define ID_DISPLAY_RIBBONS_FULL         32894
#define ID_DISPLAY_STRANDS_FULL         32895
#define ID_DISPLAY_STRANDS_OFF          32896
#define ID_SET_STRANDS_SIZE             32897
#define ID_COLOR_STRANDS                32898
#define ID_COLOR_STRANDS1               32900
#define ID_COLOR_STRANDS2               32901
#define ID_SET_STRANDS_NUMBER           32902
#define ID_COLOR_STRANDS_NONE           32903
#define ID_COLOR_RIBBONS1               32904
#define ID_COLOR_RIBBONS2               32905
#define ID_DISPLAY_WIREFRAME_FULL       32906
#define ID_DISPLAY_WIREFRAME_OFF        32907
#define ID_SET_WIREFRAME_SIZE           32908
#define ID_COLOR_BONDS_NONE             32909
#define ID_SET_DOTS_DENSITY             32910
#define ID_COLOR_DOTS_POTENTIAL         32911
#define ID_COLOR_DOTS_NONE              32913
#define ID_DOTS_VDWAALS                 32914
#define ID_DOTS_CONOLLY                 32915
#define ID_DOTS_RADIUS                  32916
#define ID_DISPLAY_WIREFRAME_TYPE       32917
#define ID_DISPLAY_WIREFRAME_DASH       32918
#define ID_DISPLAY_WIREFRAME_WIRE       32919
#define ID_DISPLAY_WIREFRAME_CYLINDER   32920
#define ID_DISPLAY_BACKBONE_OFF         32921
#define ID_DISPLAY_BACKBONE_FULL        32922
#define ID_DISPLAY_BACKBONE_WIRE        32923
#define ID_DISPLAY_BACKBONE_DASH        32924
#define ID_DISPLAY_BACKBONE_CYLINDER    32925
#define ID_SET_BACKBONE_SIZE            32926
#define ID_COLOR_BACKBONE               32927
#define ID_COLOR_BACKBONE_NONE          32928
#define ID_DISPLAY_SPACEFILL_OFF        32929
#define ID_DISPLAY_SPACEFILL_FULL       32930
#define ID_SPACEFILL_FIXEDRADIUS        32931
#define ID_SPACEFILL_VANDERWAALS        32932
#define ID_SPACEFILL_TEMPERATURE        32933
#define ID_SPACEFILL_USER               32934
#define ID_COLOR_FADE                   32935
#define ID_COLOR_SSBONDS_NONE           32936
#define ID_DISPLAY_SSBONDS_WIRE         32937
#define ID_DISPLAY_SSBONDS_DASH         32938
#define ID_DISPLAY_SSBONDS_CYLINDER     32939
#define ID_DISPLAY_HBONDS_WIRE          32940
#define ID_DISPLAY_HBONDS_DASH          32941
#define ID_DISPLAY_HBONDS_CYLINDER      32942
#define ID_DISPLAY_HBONDS_ON            32943
#define ID_DISPLAY_SSBONDS_OFF          32944
#define ID_DISPLAY_HBONDS_OFF           32945
#define ID_COLOR_HBONDS_NONE            32946
#define ID_DISPLAY_WIREFRAME_ONLY       32947
#define ID_DISPLAY_HBONDS_SIDECHAIN     32948
#define ID_DISPLAY_HBONDS_BACKBONE      32949
#define ID_DISPLAY_SSBONDS_SIDECHAIN    32950
#define ID_DISPLAY_SSBONDS_BACKBONE     32951
#define ID_RIBBONS_ON                   32952
#define ID_RIBBONS_OFF                  32953
#define ID_RIBBONS_ONLY                 32954
#define ID_RIBBONS_RIBBONS              32955
#define ID_RIBBONS_STRANDS              32956
#define ID_RIBBONS_TRACE                32957
#define ID_RIBBONS_CARTOONS             32958
#define ID_RIBBONS_BACKBONE             32959
#define ID_RIBBONS_SIZE                 32960
#define ID_RIBBONS_COLOR_NONE           32961
#define ID_RIBBONS_COLOR_INSIDE         32962
#define ID_RIBBONS_COLOR                32963
#define ID_RIBBONS_COLOR_OUTSIDE        32964
#define ID_RIBBONS_STRUCTURE            32965
#define ID_DISPLAY_TRACE_DOTS           32966
#define ID_DISPLAY_TRACE_TEMPERATURE    32967
#define ID_SET_CARTOONS_HEIGTH          32968
#define ID_SET_CARTOONS_HEIGHT          32969
#define ID_DISPLAY_RIBBONS_STRUCTURE    32970
#define ID_DISPLAY_CARTOONS_ARROW       32971
#define ID_MOLECULE_INFO                32973
#define ID_SELECT_PREVIOUS              32974
#define ID_LABELS_SETTINGS              32975
#define ID_MOLECULE_CONNECT             32976
#define ID_MOLECULE_RENUMBER            32977
#define ID_DISPLAY_BOUNDBOX             32978
#define ID_DISPLAY_UNITCELL             32979
#define ID_SELECT_BONDMODE              32980
#define ID_COLOR_HBONDS_TYPE            32981
#define ID_SELECT_INVERSE               32982
#define ID_SAVE_MOLECULARFILE           32983
#define ID_SAVE_SCRIPT                  32984
#define ID_SAVE_IMAGE                   32985
#define ID_FILE_LOAD_RASMOLSCRIPT       32986
#define ID_SET_CONNECT                  32987
#define ID_FILE_LOAD_MOLECULARFILE      32988
#define ID_FILE_RASTOP                  32989
#define ID_MOLECULE_FILE                32991
#define ID_FILE_PREFERENCES             32992
#define ID_PICK_ATOM                    32997
#define ID_PICK_GROUP                   32998
#define ID_PICK_CHAIN                   32999
#define ID_PICK_CENTRE                  33000
#define ID_PICK_LABEL                   33002
#define ID_PICK_DISTANCE                33003
#define ID_PICK_MONITOR                 33005
#define ID_PICK_ANGLE                   33006
#define ID_PICK_TORSION                 33007
#define ID_SELECT_RANGE                 33008
#define ID_SELECT_DOTS                  33009
#define ID_DISTANCE_REMOVE              33010
#define ID_DISTANCE_SHOW                33011
#define ID_MONITOR_COLOUR               33012
#define ID_MONITOR_COLOUR_NONE          33013
#define ID_COLOR_LABELS_NONE            33014
#define ID_COLOR_AXE                    33015
#define ID_COLOR_BOX                    33016
#define ID_SET_BONDS                    33017
#define ID_DISPLAY_SSBONDS_ON           33018
#define ID_COMMANDVIEW                  33019
#define ID_SELECT_EXPRESSION            33020
#define ID_SELECT_WITHIN                33021
#define ID_EXP_NEW                      33022
#define ID_EXP_ADD                      33023
#define ID_EXP_REMOVE                   33024
#define ID_EXP_EXCLUDE                  33025
#define ID_EXP_EXTRACT                  33026
#define ID_RESTRICT                     33028
#define ID_SELECTION_NEW                33029
#define ID_SELECTION_ADD                33030
#define ID_SELECTION_REMOVE             33031
#define ID_SELECTION_EXTRACT            33032
#define ID_SELECTION_EXCLUDE            33033
#define ID_SELECT_DEFINE                33035
#define ID_COPY_SELECTION               33036
#define ID_PASTE                        33037
#define ID_WINDOW_TILE                  33038
#define ID_SPACEFILL_SPHERE             33039
#define ID_SPACEFILL_STAR               33040
#define ID_PICK_COORD                   33041
#define ID_COLOUR_MODEL                 33042
#define ID_COLOUR_ALT                   33043
#define ID_SET_CISANGLE                 33044
#define ID_VIEW_MENU                    33045
#define ID_SET_BONDMODE_NONE            33046
#define ID_SET_BONDMODE_NOBONDED        33047
#define ID_SET_BONDMODE_ALL             33048
#define ID_SHOW_SELECT_CHN              33049
#define ID_SHOW_SELECT_GRP              33050
#define ID_SHOW_SELECT_ATM              33051
#define ID_MOLECULE_PHIPSI              33052
#define ID_MOLECULE_RPP                 33053
#define ID_SHOW_SELECT_COOR             33054
#define ID_COPY_POSITION                33055
#define ID_SELECT_MODEL                 33056
#define ID_COPY_IMAGE                   33057
#define ID_SLAB_AUTODEPTHCUE            33058
#define ID_DOTS_SIZE                    33059
#define ID_SET_DOTS_SIZE                33060
#define ID_HIDDEN_SEPARATOR             33061
#define ID_VIEW_LIGHTSOURCE             33062
#define ID_DISPLAY_STAR                 33080
#define ID_DISPLAY_SPHERE               33081
#define ID_DISPLAY_NOTHING              33082
#define ID_SELECT_CENTRE                33086
#define ID_PICK_ROTBOND                 33087
#define ID_PICK_MOLSET                  33088
#define ID_PICK_LIGHT                   33089
#define ID_PICK_BOND                    33091
#define ID_DISPLAY_WORLDAXES            33092
#define ID_SET_STEREO_ANGLE             33093
#define ID_MOLECULE_HIDEORSHOW          33094
#define ID_MOLECULE_SHOW                33095
#define ID_CENTRE_WORLD                 33096
#define ID_CENTRE_ORIGIN                33097
#define ID_CENTRE_ORIGINTOCENTRE        33098
#define ID_SLAB                         33099
#define ID_SLAB_RESET                   33100
#define ID_DEPTH                        33101
#define ID_DEPTH_RESET                  33102
#define ID_FILE_MOLECULE_AS             33104
#define ID_FILE_ADD                     33105
#define ID_MOLECULE_DELETE              33106
#define ID_RESET_BOND                   33107
#define ID_COORD_CHANGE                 33108
#define ID_WORLD_INFO                   33110
#define ID_SET_PREFERENCES              33111
#define ID_DEPTHCUEMODE1                33112
#define ID_DEPTHCUEMODE2                33113
#define ID_DEPTHCUEMODE3                33114
#define ID_DEPTHCUEMODE4                33115
#define ID_DEPTH_WORLD                  33116
#define ID_CENTRE_CENTRETOORIGIN        33117
#define ID_COMMANDLINE_ECHO             33118
#define ID_REPRESENTATION               33119
#define IDS_LOCAL_CMDWND                33120
#define IDS_LOCAL_COLWND                33121
#define IDS_LOCAL_MAINWND               33122
#define IDS_LOCAL_SELWND                33123
#define IDS_LOCAL_SCRWND                33124
#define IDS_LOCAL_CLIP                  33125
#define IDS_LOCAL_CHAIN                 33126
#define IDS_LOCAL_MODEL                 33127
#define IDS_LOCAL_COMOL                 33128
#define IDS_LOCAL_COWRLD                33129
#define IDS_LOCAL_COSCREEN              33130
#define IDS_LOCAL_COABS                 33131
#define IDS_LOCAL_OFF                   33132
#define IDS_LOCAL_DEF1                  33133
#define IDS_LOCAL_DEF2                  33134
#define IDS_LOCAL_DEL                   33135
#define IDS_LOCAL_WITH1                 33136
#define IDS_LOCAL_WITH2                 33137
#define IDS_LOCAL_NUM1                  33138
#define IDS_LOCAL_NUM2                  33139
#define IDS_LOCAL_CIS1                  33140
#define IDS_LOCAL_CIS2                  33141
#define IDS_LOCAL_RAD1                  33142
#define IDS_LOCAL_RAD2                  33143
#define IDS_LOCAL_WIRE1                 33144
#define IDS_LOCAL_WIRE2                 33145
#define IDS_LOCAL_HB1                   33146
#define IDS_LOCAL_HB2                   33147
#define IDS_LOCAL_SSB1                  33148
#define IDS_LOCAL_SSB2                  33149
#define IDS_LOCAL_RIBB1                 33150
#define IDS_LOCAL_RIBB2                 33151
#define IDS_LOCAL_RIBB3                 33152
#define IDS_LOCAL_RIBB4                 33153
#define IDS_LOCAL_CYL1                  33154
#define IDS_LOCAL_CYL2                  33155
#define IDS_LOCAL_CYL3                  33156
#define IDS_LOCAL_STRAND1               33157
#define IDS_LOCAL_STRAND2               33158
#define IDS_LOCAL_CAR1                  33159
#define IDS_LOCAL_CAR2                  33160
#define IDS_LOCAL_DOT1                  33161
#define IDS_LOCAL_DOT2                  33162
#define IDS_LOCAL_DD1                   33163
#define IDS_LOCAL_DD2                   33164
#define IDS_LOCAL_DRAD1                 33165
#define IDS_LOCAL_DRAD2                 33166
#define IDS_LOCAL_STEREO1               33167
#define IDS_LOCAL_STEREO2               33168
#define IDS_LOCAL_DWORLD1               33169
#define IDS_LOCAL_DWORLD2               33170
#define IDW_SELECTBAR                   59393
#define ID_VIEW_SELECTBAR               59394
#define IDW_SCRIPTBAR                   59395
#define ID_VIEW_SCRIPTBAR               59396
#define IDW_COLORBAR                    59397
#define ID_VIEW_COLORBAR                59398
#define ID_VIEW_COMMANDLINE             59399

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         33120
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           122
#endif
#endif
